### ISSUE TITLE
No module named 'efficiency'

### ISSUE THREAD

**Issue by ipp123456** [thomas0809/GraphIE#1]
Good job!
It seems to be missing of some files when I run the word-level/examples/multi_run_conll.py

Traceback (most recent call last):
  File "E:/GraphIE-master/word-level/examples/multi_runs_conll.py", line 5, in <module>
    from efficiency.log import show_time, del_quote
ModuleNotFoundError: No module named 'efficiency'

Thanks!

**Comment by zhijing-jin** [comment]
Hi thanks for the question!

I've added a detailed readme.md here: https://github.com/thomas0809/GraphIE/tree/master/word-level

Please let me know if this works for you:
```
git pull
cd ./word-level/
pip install -r requirements.txt
# then follow the readme.md :)
```
