### ISSUE TITLE
Run error?

### ISSUE THREAD

**Issue by DesireHope** [thomas0809/GraphIE#2]
run multi-runs_conll, there's error:

Traceback (most recent call last):
  File "examples/NERCRF_conll.py", line 548, in <module>
    main()
  File "examples/NERCRF_conll.py", line 240, in main
    cheat_densify=cheat_densify)
  File "./neuronlp2/io/conll03_data.py", line 146, in read_data
    inst = reader.getNext(unk_replace, normalize_digits, graph_model)
  File "./neuronlp2/io/reader.py", line 220, in getNext
    for sent in words])
  File "./neuronlp2/io/reader.py", line 220, in <listcomp>
    for sent in words])
  File "/home/ubuntu/anaconda3/envs/dp-py3-env/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 1377, in pad
    newmat = _append_const(newmat, pad_after, after_val, axis)
  File "/home/ubuntu/anaconda3/envs/dp-py3-env/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 142, in _append_const
    (arr, (np.zeros(padshape) + val).astype(arr.dtype)), axis=axis)
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

**Comment by zhijing-jin** [comment]
Hi,

Thanks for reporting the error. It seems to be a problem of the running environment.

There might be two solutions: (1) check the numpy version, (2) adapt the code under your running environment.

(1) May I know your numpy version? The one I used is 'numpy 1.15.4'

(2) Here are some hints when locally solving the problem:

In the error message, `dtype('<U32')` is a string format. It seems that somewhere during the code execution, a string is not turned properly into a number. (reference problem: https://blog.csdn.net/ztf312/article/details/79419553; another reference: https://stackoverflow.com/questions/44527956/python-ufunc-add-did-not-contain-a-loop-with-signature-matching-types-dtype?rq=1)

In the code, it seems to be this line executing `np.pad` that you can take care of
```
// line 215 of ./word-level/neuronlp2/io/reader.py
        # (5) words
        words_padded = np.vstack([
            np.pad(sent,
                   pad_width=[(0, sent_len - len(sent))],
                   mode='constant', constant_values=PAD_WORD)
            for sent in words])
```

Maybe you can use print out the `sent` before and after `np.pad` to locate the error.

Hope these suggestions help you better solve the problem!

**Comment by DesireHope** [comment]
Thank you
